In [1]:
#import dependencies
from RealtyModule import Get_Zillow_Data, Get_Homes
import pandas as pd
import numpy as np
zkey = 'X1-ZWz1hey97qto23_4lr3d'

In [2]:
home_city = input("What city is your ideal home located in? ")

In [2]:
#get list of homes (be patient!)
homes = Get_Homes('atlanta-ga')
print("Get Homes Done!")

Get Homes Done!

In [4]:
#Get zillow data for first 5 in list
addresses = []
zipcodes =[]
prices = []
estimates = []
sizes = []
footages = []
rooms = []
baths = []
yearbuilt = []
hometype = []

n=0
for home in homes:
    addresses.append(home['Address'])
    zipcodes.append(home['Zip Code'])
    prices.append(home['Asking Price'])
    ZillowData = Get_Zillow_Data(home['Address'], home['Zip Code'], zkey)
    estimates.append(ZillowData['Zestimate'])
    sizes.append(ZillowData['Lot Size'])
    footages.append(ZillowData['Square Feet'])
    rooms.append(ZillowData['Bedrooms'])
    baths.append(ZillowData['Bathrooms'])
    yearbuilt.append(ZillowData['Year Built'])
    hometype.append(ZillowData['Home Type'])
    
    n+=1
    if n == 20:
        break
        
print('API calls complete!')

In [5]:
#Build dataframe
HouseHuntersDF = pd.DataFrame({'Address':addresses,
                               'Zip Code':zipcodes,
                               'Asking Price':prices,
                               'Zestimate':estimates,
                               'Lot Size (in acres)':sizes,
                               'Square Feet':footages,
                               'Bedrooms':rooms,
                               'Bathrooms':baths,
                               'Year Built': yearbuilt,
                               'Home Type': hometype})

#HouseHuntersDF["Lot Size (in acres)"] = HouseHuntersDF["Lot Size (in acres)"].map("{:.2f}".format)
HouseHuntersDF['Asking Price'] = HouseHuntersDF['Asking Price'].astype(str).str.replace(',','').str.extract('(\d+)')

HouseHuntersDF.head()

,Address,Zip Code,Asking Price,Zestimate,Lot Size (in acres),Square Feet,Bedrooms,Bathrooms,Year Built,Home Type
0,"3085 Eastbrook Ter SW, Atlanta, GA",30331,349900,None,10018,3636,6,4.0,2008,SingleFamily
1,"5524 Stone Cove Dr SW, Atlanta, GA",30331,317000,312517,14374,5002,6,4.0,2007,SingleFamily
2,"3300 Ferncliff Ln, Atlanta, GA",30324,527900,518322,871,1872,3,4.0,2012,Condominium
3,"2871 Overlook Way, Atlanta, GA",30324,470000,465603,2221,2220,3,4.0,2007,Condominium
4,"45 Ivan Allen Jr Blvd NW UNIT 1901, Atlanta, GA",30308,545000,533631,1773,1774,2,3.0,2010,Condominium
5,"229 Woodward Ave SE, Atlanta, GA",30312,487900,466183,2610,2040,4,3.0,2016,SingleFamily
6,"347 Ardmore Ct NW, Atlanta, GA",30309,560900,546669,871,2195,4,4.0,2011,Condominium
7,"943 Peachtree St NE UNIT 1215, Atlanta, GA",30309,282900,279170,767,768,1,1.0,2002,Condominium
8,"485 Hillside Dr NW, Atlanta, GA",30342,1250000,1187258,44914,4399,5,5.0,1955,SingleFamily
9,"3220 Camden Ct, Atlanta, GA",30349,278990,271018,9147,2522,4,3.0,2019,SingleFamily
10,"74 Richardson St SE, Atlanta, GA",30312,407000,399213,5749,1812,4,3.0,2000,SingleFamily
11,"384 Ralph Mcgill Blvd NE UNIT 105, Atlanta, GA",30312,278999,272799,None,1088,2,2.0,2006,Condominium
12,"587 Virginia Ave NE APT 806, Atlanta, GA",30306,303000,295373,802,800,2,2.0,1990,Condominium
13,"1922 Greystone Rd NW, Atlanta, GA",30318,675000,656652,12249,2011,3,3.0,1940,SingleFamily
14,"3334 Peachtree Rd NE APT 713, Atlanta, GA",30326,237000,235386,998,998,1,1.0,1997,Condominium
15,"1255 Danner St SE, Atlanta, GA",30316,439900,422589,7492,2400,3,2.0,2004,SingleFamily
16,"3116 Benninger Trce SW, Atlanta, GA",30331,188000,185328,6171,1237,3,2.5,2007,SingleFamily
17,"1015 Mayson Turner Rd NW, Atlanta, GA",30314,299449,289992,6320,1940,4,3.0,2003,SingleFamily
18,"591 Moreland Ave SE, Atlanta, GA",30316,419000,406316,7344,1235,2,2.0,1920,SingleFamily
19,"195 Arizona Ave NE UNIT 148, Atlanta, GA",30307,273900,258112,None,1354,1,2.0,2003,Condominium

In [6]:
home_price = input("What is your ideal price? ")
home_lot_size = input("What is your ideal lot size? ")
home_footage = input("What is your ideal square footage? ")
home_beds = input("What is your ideal number of bedrooms? ")
home_baths = input("What is your ideal number of bathrooms? ")
home_year = input("What is your ideal build year? ")
home_type = input("What is your ideal home type? ")

In [6]:

weights = list(np.arange(1,6,1))
usedweights = []

user_price = int(input('For the home price, assign a number from 1-5, to indicate the importance of this category. (5 being most important, 1 being least)'))
if user_price not in weights:
    if user_price in usedweights:
        user_price = input(f'You have already used this value. Pick another. Your Options are {weights}')
    else:
        user_price = input(f'That is not a value in the range. Your Options are {weights}')
else:
    usedweights.append(user_price)
    weights.remove(user_price)
    
user_lot_size = int(input('For the home price, assign a number from 1-5, to indicate the importance of this category. (5 being most important, 1 being least)'))
if user_lot_size not in weights:
    if user_lot_size in usedweights:
        user_lot_size = input(f'You have already used this value. Pick another. Your Options are {weights}')
    else:
        user_lot_size =  input(f'That is not a value in the range. Your Options are {weights}')
else:
    usedweights.append(user_lot_size)
    weights.remove(user_lot_size)

user_sq_ft = int(input('For the home price, assign a number from 1-5, to indicate the importance of this category. (5 being most important, 1 being least)'))
if user_sq_ft not in weights:
    if user_sq_ft in usedweights:
        user_sq_ft = input(f'You have already used this value. Pick another. Your Options are {weights}')
    else:
        user_sq_ft = input(f'That is not a value in the range. Your Options are {weights}')
else:
    usedweights.append(user_sq_ft)
    weights.remove(user_sq_ft)

user_bedrooms = int(input('For the number of bedrooms, assign a number from 1-5, to indicate the importance of this category. (5 being most important, 1 being least)'))
if user_bedrooms not in weights:
    if user_bedrooms in usedweights:
        user_bedrooms = input(f'You have already used this value. Pick another. Your Options are {weights}')
    else:
        user_bedrooms = input(f'That is not a value in the range. Your Options are {weights}')
else:
    usedweights.append(user_bedrooms)
    weights.remove(user_bedrooms)

user_bathrooms = int(input('For the number of bathrooms, assign a number from 1-5, to indicate the importance of this category. (5 being most important, 1 being least)'))
if user_bathrooms not in weights:
    if user_bathrooms in usedweights:
        user_bathrooms = input(f'You have already used this value. Pick another. Your Options are {weights}')
    else:
        user_bathrooms = input(f'That is not a value in the range. Your Options are {weights}')
else:
    usedweights.append(user_bathrooms)
    weights.remove(user_bathrooms)

user_weights = {"price": (user_price * 2 / 10) + 1,
               "lot_size": (user_lot_size * 2 / 10) + 1, 
               "sq_ft": (user_sq_ft * 2 / 10) + 1, 
               "bedrooms": (user_bedrooms * 2 / 10) + 1,
               "bathrooms": (user_bathrooms * 2 / 10) + 1}

What city is your ideal home located in?  atlanta
What is your ideal price?  300000
What is your ideal lot size?  2000
What is your ideal square footage?  2000
What is your ideal number of bedrooms?  3
What is your ideal number of bathrooms?  2
What is your ideal build year?  1997
What is your ideal home type?  SingleFamily

In [7]:
#Convert these input values to integer type
home_price = float(home_price)
home_lot_size = float(home_lot_size)
home_beds = int(home_beds)
home_baths = int(home_baths)
home_year = int(home_year)
home_footage = int(home_footage)

In [181]:
#Create Data Frame for Price Input
HouseHunters_Input_1 = HouseHuntersDF[HouseHuntersDF['Asking Price'].astype(int)>=home_price]
HouseHunters_Input_1

#Create Data Frame for Home Lot Size Input Using Previous Input Data Frame
HouseHunters_Input_2 = HouseHunters_Input_1.loc[HouseHunters_Input_1['Lot Size (in acres)'].astype(float)>=home_lot_size]
HouseHunters_Input_2

#Create Data Frame for Square Footage Input Using Previous Input Data Frame
HouseHunters_Input_3 = HouseHunters_Input_2.loc[HouseHunters_Input_2['Square Feet'].astype(int)>=home_footage]
HouseHunters_Input_3

#Create Data Frame for Bedrooms Input Using Previous Input Data Frame

HouseHunters_Input_4 = HouseHunters_Input_3.loc[HouseHunters_Input_3['Bedrooms'].astype(int)>=home_beds]
HouseHunters_Input_4

#Create Data Frame for Bathrooms Using Previous Input Data Frame
HouseHunters_Input_5 = HouseHunters_Input_4.loc[HouseHunters_Input_4['Bathrooms'].astype(float)>=home_baths]
HouseHunters_Input_5

#Create Data Frame for Home Year Input Using Previous Input Data Frame
HouseHunters_Input_6 = HouseHunters_Input_5.loc[HouseHunters_Input_5['Year Built'].astype(int)>=home_year]
HouseHunters_Input_6

#Create Data Frame for Home Type Input Using Previous Input Data Frame
HouseHunters_Input_7 = HouseHunters_Input_6.loc[HouseHunters_Input_6['Home Type'].astype(str)>=home_type]
HouseHunters_Input_7 = HouseHunters_Input_7.reset_index(drop=True)
HouseHunters_Input_7

In [181]:
# Normalize the values within this dataframe
scaledDF = HouseHunters_Input_7

columnlist = ['Lot Size (in acres)', 'Square Feet', 'Bedrooms', 'Bathrooms']
for column in columnlist:
    
    #Get Min and Max Values
    Max = float(scaledDF[column].max())
    Min = float(scaledDF[column].min())
    for i in range(len(scaledDF[column])):
        if float(scaledDF[column].iloc[i]) > Max:
            Max = float(scaledDF[column].iloc[i])
        elif float(scaledDF[column].iloc[i]) < Min:
            Min = float(scaledDF[column].iloc[i])
    
    #Scale all values to 1-10
    New_Values = []
    for i in range(len(scaledDF[column])):
        item = float(scaledDF[column].iloc[i])
        if item == Max:
            new_item = 10
        elif item == Min:
            new_item = 1
        else:
            new_item = 10 * (item - Min) / (Max - Min)
        New_Values.append(new_item)
    scaledDF[column] = New_Values

# 'Asking Price' scaling
column = 'Asking Price'
Max = float(scaledDF[column].max())
Min = float(scaledDF[column].min())
for i in range(len(scaledDF[column])):
    if float(scaledDF[column].iloc[i]) > Max:
        Max = float(scaledDF[column].iloc[i])
    elif float(scaledDF[column].iloc[i]) < Min:
        Min = float(scaledDF[column].iloc[i])
#Scale all values to 1-10
New_Values = []
for i in range(len(scaledDF[column])):
    item = float(scaledDF[column].iloc[i])
    if item == Max:
        new_item = 1
    elif item == Min:
        new_item = 10
    else:
        new_item = 10 * (Max - item) / (Max - Min)
    New_Values.append(new_item)
scaledDF[column] = New_Values

#Create a column scoring each home on its attributes
scores = []
for i in scaledDF.index:
    score = scaledDF['Asking Price'].iloc[i] + scaledDF['Lot Size (in acres)'].iloc[i] + scaledDF['Square Feet'].iloc[i] + scaledDF['Bedrooms'].iloc[i] + scaledDF['Bathrooms'].iloc[i]
    scores.append(score)
HouseHunters_Input_7['Scores'] = scores
HouseHunters_Input_7